source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/dorada/PodSpecs.git'

use_frameworks!

target 'DRHelpAndSupportViewController_Example' do
  pod 'DRHelpAndSupportViewController', :path => '../'
end

target 'DRHelpAndSupportViewController_Tests' do
  pod 'DRHelpAndSupportViewController', :path => '../'

end
